### ISSUE TITLE
Native Image generation fails because of referenced aws-java-sdk-core using java.util.Random

### ISSUE THREAD

**Issue by timguy** [quarkiverse/quarkus-amazon-alexa#50]
Hi thanks for the plugin, but I get the following error when trying to build a native image:
`
gradlew build -x test -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args="--initialize-at-run-time=com.amazonaws.retry.PredefinedBackoffStrategies --trace-object-instantiation=java.util.Random"`

```
[1/7] Initializing...                                                                                   (11,1s @ 0,15GB)
 Version info: 'GraalVM 22.2.0 Java 17 CE'
 Java version info: '17.0.4+8-jvmci-22.2-b06'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 ....
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:82)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:138)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:89)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:79)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:82)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:138)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:89)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:79)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.error(DisallowedImageHeapObjectFeature.java:173)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.image.DisallowedImageHeapObjects.check(DisallowedImageHeapObjects.java:62)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.replacer(DisallowedImageHeapObjectFeature.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObject$3(ImageHeapScanner.java:272)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 10 more
```
The reason is the java.util.Random used in com.amazonaws.retry.PredefinedBackoffStrategies and com.amazonaws.ClientConfiguration  (aws-java-sdk-core-1.11.420.jar) which is fetched by io.quarkiverse.amazonalexa:quarkus-amazon-alexa:1.0.3

```
quarkusDevBaseRuntimeClasspathConfiguration
+--- io.quarkus.platform:quarkus-bom:2.12.1.Final
+--- io.quarkiverse.amazonalexa:quarkus-amazon-alexa:1.0.3
|    +--- io.quarkus:quarkus-apache-httpclient:2.10.0.Final -> 2.12.1.Final
|    |    +--- io.quarkus:quarkus-arc:2.12.1.Final (*)
|    |    +--- org.apache.httpcomponents:httpclient:4.5.13
|    |    |    +--- org.apache.httpcomponents:httpcore:4.4.13 -> 4.4.15
|    |    |    \--- commons-codec:commons-codec:1.11 -> 1.15
|    |    \--- org.jboss.logging:commons-logging-jboss-logging:1.0.0.Final
|    |         \--- org.jboss.logging:jboss-logging:3.3.1.Final -> 3.5.0.Final
|    +--- com.amazon.alexa:ask-sdk:2.43.7          Juni 22   -  2.44.0 Ende August
|    |    +--- com.amazon.alexa:ask-sdk-core:2.43.7
|    |    |    +--- com.amazon.alexa:ask-sdk-runtime:2.43.7
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.6 -> 2.13.3 (*)
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.6.1 -> 2.13.3 (*)
|    |    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.6 -> 2.13.3 (*)
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.6 -> 2.13.3 (*)
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
|    |    |    +--- com.amazon.alexa:ask-sdk-model:1.39.4
|    |    |    |    \--- com.amazon.alexa:ask-sdk-model-runtime:1.0.5
|    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.10.4 -> 2.13.3 (*)
|    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.10.4 -> 2.13.3 (*)
|    |    |    |         \--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.4 -> 2.13.3 (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.36
|    |    +--- com.amazon.alexa:ask-sdk-lambda-support:2.43.7
|    |    |    +--- com.amazon.alexa:ask-sdk-runtime:2.43.7 (*)
|    |    |    +--- com.amazonaws:aws-lambda-java-core:1.2.1
|    |    |    \--- commons-io:commons-io:2.7 -> 2.11.0
|    |    +--- com.amazon.alexa:ask-sdk-servlet-support:2.43.7
|    |    |    +--- com.amazon.alexa:ask-sdk-core:2.43.7 (*)
|    |    |    +--- commons-codec:commons-codec:1.6 -> 1.15
|    |    |    +--- commons-io:commons-io:2.7 -> 2.11.0
|    |    |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.36
|    |    +--- com.amazon.alexa:ask-sdk-dynamodb-persistence-adapter:2.43.7
|    |    |    +--- com.amazon.alexa:ask-sdk-core:2.43.7 (*)
|    |    |    \--- com.amazonaws:aws-java-sdk-dynamodb:1.11.420		###################################
|    |    |         +--- com.amazonaws:aws-java-sdk-s3:1.11.420
|    |    |         |    +--- com.amazonaws:aws-java-sdk-kms:1.11.420
|    |    |         |    |    +--- com.amazonaws:aws-java-sdk-core:1.11.420             ###################################
```

**What I tried**

gradlew build -x test -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args="--initialize-at-run-time=com.amazonaws.retry.PredefinedBackoffStrategies --initialize-at-run-time=com.amazonaws.ClientConfiguration --trace-object-instantiation=java.util.Random"
but got the same errors.

Question
- how to get rid of the error? For sure it is somehow possible with command line
- At longterm. Would it be possible to fix it in here? io.quarkiverse.amazonalexa:quarkus-amazon-alexa:1.0.3

**Comment by gsmet** [comment]
Hum. The test that has been added is actually testing nothing :/ - https://github.com/quarkiverse/quarkus-amazon-alexa/blob/main/integration-tests/src/main/java/io/quarkiverse/amazonalexa/it/AmazonAlexaResource.java
What's weird though is that even with the test doing nothing, I would have expected the problem to be reported when building the native executable on CI.

Would you mind trying to add an actual test that reproduces your issue? I have no idea if it's doable to have Alexa tests without actually connecting to an external service (we don't want that) but we really need a test to make sure we don't have regressions like that.

**Comment by timguy** [comment]
I got it running now. 
My syntax was wrong (initialize-at-run-time seperated by commata) and there are 3 classes:
`
gradlew build -x test -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args="--initialize-at-run-time=com.amazonaws.retry.PredefinedBackoffStrategies, --initialize-at-run-time=com.amazonaws.retry.PredefinedRetryPolicies, --initialize-at-run-time=com.amazonaws.ClientConfiguration, --trace-object-instantiation=java.util.Random"`

Well about the test. Wouldn't know how to test it in a junit test.
Would be just this gradle statement in some build pipeline.

I don't know why nobody had this issue. Maybe not using native (but for me this was the reason to use quarkus).
I read somewhere that GraalVM was going more strict with Random class since some versions.
For me case is closed. But keep ticket open if you want to add test or initialize-at-run-time by quarkus-amazon-alexa.
Thanks

**Comment by gsmet** [comment]
Do you have an example of what you're doing with Alexa that wasn't working?

**Comment by timguy** [comment]
Just read that you was using a native build for the test case. 
The reason could be that your test is not using something out of com.amazon.alexa:ask-sdk-dynamodb-persistence-adapter:2.43.7 (which fetches com.amazonaws:aws-java-sdk-core:1.11.420). That could be the reason that you don't got any complains.
My approach was as follows: 
- https://code.quarkus.io/?b=GRADLE&e=io.quarkiverse.amazonalexa%3Aquarkus-amazon-alexa&extension-search=origin:platform%20alexa
- download the zip
- overwrite all of my existing project/skill. My skill is using dynamodb classes (e.g.: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable)

So maybe add something with dynamodb in the test skill and it will break.

```
public class DynamoDBService {
			.getLogger(AmazonDynamoDBClient.class);
	private DynamoDBMapper mapper;

	public DynamoDBService() {
		this(Regions.EU_WEST_1, "https://dynamodb.eu-west-1.amazonaws.com");
	}
}	

```

**Comment by gsmet** [comment]
I created https://github.com/quarkiverse/quarkus-amazon-alexa/pull/51 .

I will merge once it's green and release 1.0.5. That way you will be able to get rid of your specific config and others will also benefit from it.

**Comment by gsmet** [comment]
I pushed the release button for 1.0.4. It looks like there are some sync issues with Maven Central but it will end up there eventually.
Could you please report back when you're able to upgrade? It should hit Central by tomorrow.

**Comment by gsmet** [comment]
1.0.4 has hit Maven Central.

**Comment by timguy** [comment]
✔️ Tested with 1.0.4.
- No more need of --initialize-at-run-time
- thanks for https://github.com/quarkiverse/quarkus-amazon-alexa/pull/51
